### ISSUE TITLE
get the coefficent values - basic linear regression

### ISSUE THREAD

**Issue by andrewczgithub** [blengerich/Personalized_Regression_Neurips19#1]
hi @blengerich !!
Love this piece of work!
Really cool model.

I was just wondering if there is any way to pull back the coefficents of a learned linear regression model?

Kind regards,
Andrew

**Comment by blengerich** [comment]
Hi @andrewczgithub! - thank you for the kind words!

The `DistanceMatching.fit()` function returns Z, Q where ZQ is the matrix of learned models. Each row in the ZQ matrix is the coefficients of that personalized model.

Also, each `DistanceMatching` object stores this matrix in the attribute `beta_hat`, so it can also be retrieved without multiplication.

**Comment by andrewczgithub** [comment]
Hi @blengerich !!

Thank you so much! the model is awesome!
I will experiment with it and get back to you.

This issue can now be closed :)

cheers again!
Best,
Andrew
